apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template-service.fullname" . }}-config
  labels:
    {{- include "template-service.labels" . | nindent 4 }}
data:
  db.host: {{ .Values.database.host | quote }}
  db.port: {{ .Values.database.port | quote }}
  db.name: {{ .Values.database.name | quote }}
