{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "serivce-trade.fullname" . }}-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: service-trade.rules
      rules:
        - alert: ServiceTradeHigh5xxErrorRate
          expr: |
            100 *
            sum(rate(http_server_requests_seconds_count{
              application="service-trade",
              status=~"5.."
            }[1m]))
            /
            sum(rate(http_server_requests_seconds_count{
              application="service-trade"
            }[1m]))
            > 5
          for: 1m
          labels:
            severity: critical
            service: service-trade
          annotations:
            summary: "Service Trade 5xx error rate high"
            description: "service-trade 5xx error rate > 5% for 1 minute"
  {{- end }}

