apiVersion: v1
kind: Secret
metadata:
  name: {{ include "serivce-trade.fullname" . }}-secret
  labels:
    {{- include "serivce-trade.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-user: {{ .Values.database.user | quote }}
  db-password: {{ .Values.database.password | quote }}
  {{- if .Values.redis }}
  redis-password: {{ .Values.redis.password | quote }}
  {{- end }}
