apiVersion: v1
kind: ConfigMap
metadata:
  name: trade-config
data:
  db.host: "mysql-service"
  db.port: "3306"
  db.name: "passit_db"
  application.yml: |
    spring:
      application:
        name: trade-service
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
