apiVersion: v1
kind: ConfigMap
metadata:
  name: trade-config
data:
  db.host: "postgres-service"
  db.port: "5432"
  db.name: "trade_db"
  application.yml: |
    spring:
      application:
        name: trade-service
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
